import axios from "axios";

const backendUrl = (process.env.REACT_APP_BACKEND_URL || "http://localhost:8001").replace(/\/+$/, "");
export const API_BASE = `${backendUrl}/api`;
const api = axios.create({ baseURL: API_BASE, withCredentials: true });

export const fetchCurrentUser = () => api.get("/auth/me").then((r) => r.data.user);
export const fetchSetupStatus = () => api.get("/auth/setup").then((r) => r.data.required);
export const setupOwner = (details) => api.post("/auth/setup", details).then((r) => r.data.user);
export const login = (credentials) => api.post("/auth/login", credentials).then((r) => r.data.user);
export const logout = () => api.post("/auth/logout");
export const createTechnician = (technician) => api.post("/auth/technicians", technician).then((r) => r.data.user);
export const updateTechnicianStatus = (technicianId, active) => api.patch(`/auth/technicians/${encodeURIComponent(technicianId)}`, { active }).then((r) => r.data.user);
export const deleteTechnician = (technicianId) => api.delete(`/auth/technicians/${encodeURIComponent(technicianId)}`).then((r) => r.data);
export const fetchManagers = () => api.get("/auth/managers").then((r) => r.data.managers);
export const createManager = (manager) => api.post("/auth/managers", manager).then((r) => r.data.user);
export const updateManagerStatus = (managerId, active) => api.patch(`/auth/managers/${managerId}`, { active }).then((r) => r.data.user);
export const transferOwnership = (managerId) => api.post("/auth/ownership/transfer", { managerId }).then((r) => r.data.user);
export const fetchAllData = () => api.get("/data").then((r) => r.data);
export const fetchCatalog = () => api.get("/catalog").then((r) => r.data);
export const fetchTracking = (token) => api.get(`/tracking/${token}`).then((r) => r.data);
export const fetchClinicContact = (clinicId) => api.get(`/clinics/${clinicId}/contact`).then((r) => r.data);
export const createReceivedCase = (receivedCase) => api.post("/receiving/cases", receivedCase).then((r) => r.data);
export const deleteReceivedCase = (caseId) => api.delete(`/receiving/cases/${encodeURIComponent(caseId)}`).then((r) => r.data);
export const restoreReceivedCase = (caseId) => api.post(`/receiving/cases/${encodeURIComponent(caseId)}/restore`).then((r) => r.data);
export const updateReceivedCase = (caseId, changes) => api.patch(`/receiving/cases/${encodeURIComponent(caseId)}`, changes).then((r) => r.data);
export const updateCaseAttention = (caseId, attention) => api.patch(`/receiving/cases/${encodeURIComponent(caseId)}/attention`, attention).then((r) => r.data);
export const saveReport = (report) => api.post("/reports", report).then((r) => r.data);
export const deleteReport = (reportId) => api.delete(`/reports/${encodeURIComponent(reportId)}`).then((r) => r.data);
export const createLogisticsRoute = (route) => api.post("/routes", route).then((r) => r.data);
export const addRouteStop = (routeId, stop) => api.post(`/routes/${routeId}/stops`, stop).then((r) => r.data);
export const transferRouteStop = (routeId, stopId, driverId) => api.patch(`/routes/${routeId}/stops/${stopId}/transfer`, { driverId }).then((r) => r.data);
export const deleteLogisticsRoute = (routeId) => api.delete(`/routes/${routeId}`).then((r) => r.data);
export const createClinic = (clinic) => api.post("/clinics", clinic).then((r) => r.data);
export const updateClinic = (clinicId, clinic) => api.put(`/clinics/${clinicId}`, clinic).then((r) => r.data);
export const importClinics = (clinics) => api.post("/clinics/import", { clinics }).then((r) => r.data);
export const createDriver = (driver) => api.post("/drivers", driver).then((r) => r.data);
export const updateDriver = (driverId, driver) => api.patch(`/drivers/${driverId}`, driver).then((r) => r.data);
